/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testview;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.white;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author HoaNguyenVan
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        setLocationRelativeTo(null);
        this.jpViewQLBH.setVisible(true);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        this.jpQLBH.setBackground(white);
        
        setTitle("ShirtService");
        ImageIcon imgIcon = new ImageIcon("D:\\FPT POLYTECHNIC\\SOF203\\Demo\\testView\\src\\main\\java\\com\\mycompany\\testview\\chatgpt-logo-chat-gpt-icon-on-white-background-free-vector.jpg"); // Đường dẫn tới file logo
        Image img = imgIcon.getImage();
        setIconImage(img);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpQLBH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpQLSP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpQLDM = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpQLKM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpQLKH = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpTK = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpQLTK = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jpViewQLBH = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpViewQLSP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpViewQLDM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpViewQLKM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpViewQLKH = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpViewTK = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpViewQLTK = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(java.awt.Color.white);

        jpQLBH.setBackground(new java.awt.Color(255, 102, 0));
        jpQLBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLBHMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý bán hàng");

        javax.swing.GroupLayout jpQLBHLayout = new javax.swing.GroupLayout(jpQLBH);
        jpQLBH.setLayout(jpQLBHLayout);
        jpQLBHLayout.setHorizontalGroup(
            jpQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLBHLayout.setVerticalGroup(
            jpQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jpQLSP.setBackground(new java.awt.Color(255, 102, 0));
        jpQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLSPMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý sản phẩm");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jpQLSPLayout = new javax.swing.GroupLayout(jpQLSP);
        jpQLSP.setLayout(jpQLSPLayout);
        jpQLSPLayout.setHorizontalGroup(
            jpQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLSPLayout.setVerticalGroup(
            jpQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jpQLDM.setBackground(new java.awt.Color(255, 102, 0));
        jpQLDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLDMMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý danh mục");

        javax.swing.GroupLayout jpQLDMLayout = new javax.swing.GroupLayout(jpQLDM);
        jpQLDM.setLayout(jpQLDMLayout);
        jpQLDMLayout.setHorizontalGroup(
            jpQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLDMLayout.setVerticalGroup(
            jpQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jpQLKM.setBackground(new java.awt.Color(255, 102, 0));
        jpQLKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLKMMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quản lý khuyến mãi");

        javax.swing.GroupLayout jpQLKMLayout = new javax.swing.GroupLayout(jpQLKM);
        jpQLKM.setLayout(jpQLKMLayout);
        jpQLKMLayout.setHorizontalGroup(
            jpQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLKMLayout.setVerticalGroup(
            jpQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jpQLKH.setBackground(new java.awt.Color(255, 102, 0));
        jpQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLKHMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jpQLKHLayout = new javax.swing.GroupLayout(jpQLKH);
        jpQLKH.setLayout(jpQLKHLayout);
        jpQLKHLayout.setHorizontalGroup(
            jpQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLKHLayout.setVerticalGroup(
            jpQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jpTK.setBackground(new java.awt.Color(255, 102, 0));
        jpTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpTKMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thống kê");

        javax.swing.GroupLayout jpTKLayout = new javax.swing.GroupLayout(jpTK);
        jpTK.setLayout(jpTKLayout);
        jpTKLayout.setHorizontalGroup(
            jpTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpTKLayout.setVerticalGroup(
            jpTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jpQLTK.setBackground(new java.awt.Color(255, 102, 0));
        jpQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLTKMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Quản lý tài khoản");

        javax.swing.GroupLayout jpQLTKLayout = new javax.swing.GroupLayout(jpQLTK);
        jpQLTK.setLayout(jpQLTKLayout);
        jpQLTKLayout.setHorizontalGroup(
            jpQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQLTKLayout.setVerticalGroup(
            jpQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Đăng xuất");

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\FPT POLYTECHNIC\\SOF203\\Demo\\testView\\src\\main\\java\\com\\mycompany\\testview\\logo.png")); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQLBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jpQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jpViewQLBH.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setText("View QLBH");

        javax.swing.GroupLayout jpViewQLBHLayout = new javax.swing.GroupLayout(jpViewQLBH);
        jpViewQLBH.setLayout(jpViewQLBHLayout);
        jpViewQLBHLayout.setHorizontalGroup(
            jpViewQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(jpViewQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLBHLayout.createSequentialGroup()
                    .addContainerGap(444, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        jpViewQLBHLayout.setVerticalGroup(
            jpViewQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jpViewQLBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLBHLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jpViewQLSP.setBackground(new java.awt.Color(153, 255, 102));

        jLabel8.setText("View  QLSp");

        javax.swing.GroupLayout jpViewQLSPLayout = new javax.swing.GroupLayout(jpViewQLSP);
        jpViewQLSP.setLayout(jpViewQLSPLayout);
        jpViewQLSPLayout.setHorizontalGroup(
            jpViewQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpViewQLSPLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jpViewQLSPLayout.setVerticalGroup(
            jpViewQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpViewQLSPLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel8)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jpViewQLDM.setBackground(new java.awt.Color(204, 51, 0));

        jLabel9.setText("View QLDM");

        javax.swing.GroupLayout jpViewQLDMLayout = new javax.swing.GroupLayout(jpViewQLDM);
        jpViewQLDM.setLayout(jpViewQLDMLayout);
        jpViewQLDMLayout.setHorizontalGroup(
            jpViewQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(jpViewQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLDMLayout.createSequentialGroup()
                    .addContainerGap(442, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        jpViewQLDMLayout.setVerticalGroup(
            jpViewQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jpViewQLDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLDMLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jpViewQLKM.setBackground(new java.awt.Color(51, 255, 204));

        jLabel10.setText("View QLKM");

        javax.swing.GroupLayout jpViewQLKMLayout = new javax.swing.GroupLayout(jpViewQLKM);
        jpViewQLKM.setLayout(jpViewQLKMLayout);
        jpViewQLKMLayout.setHorizontalGroup(
            jpViewQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(jpViewQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLKMLayout.createSequentialGroup()
                    .addContainerGap(443, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
        jpViewQLKMLayout.setVerticalGroup(
            jpViewQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jpViewQLKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLKMLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jpViewQLKH.setBackground(new java.awt.Color(204, 0, 204));

        jLabel11.setText("View QLKH");

        javax.swing.GroupLayout jpViewQLKHLayout = new javax.swing.GroupLayout(jpViewQLKH);
        jpViewQLKH.setLayout(jpViewQLKHLayout);
        jpViewQLKHLayout.setHorizontalGroup(
            jpViewQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(jpViewQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLKHLayout.createSequentialGroup()
                    .addContainerGap(443, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(395, Short.MAX_VALUE)))
        );
        jpViewQLKHLayout.setVerticalGroup(
            jpViewQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jpViewQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLKHLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jpViewTK.setBackground(new java.awt.Color(51, 51, 255));

        jLabel12.setText("View TK");

        javax.swing.GroupLayout jpViewTKLayout = new javax.swing.GroupLayout(jpViewTK);
        jpViewTK.setLayout(jpViewTKLayout);
        jpViewTKLayout.setHorizontalGroup(
            jpViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(jpViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewTKLayout.createSequentialGroup()
                    .addContainerGap(453, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );
        jpViewTKLayout.setVerticalGroup(
            jpViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jpViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewTKLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jpViewQLTK.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Password", "Vai trò", "Trạng thái làm việc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpViewQLTKLayout = new javax.swing.GroupLayout(jpViewQLTK);
        jpViewQLTK.setLayout(jpViewQLTKLayout);
        jpViewQLTKLayout.setHorizontalGroup(
            jpViewQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpViewQLTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpViewQLTKLayout.setVerticalGroup(
            jpViewQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpViewQLTKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpViewQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLDM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpViewQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLDM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpViewQLBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpContainerLayout = new javax.swing.GroupLayout(jpContainer);
        jpContainer.setLayout(jpContainerLayout);
        jpContainerLayout.setHorizontalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContainerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContainerLayout.setVerticalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpQLBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLBHMouseClicked
        this.jpViewQLBH.setVisible(true);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        
        
        this.jpQLBH.setBackground(white);
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLBHMouseClicked

    private void jpQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLSPMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(true);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        
        
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(white);
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLSPMouseClicked

    private void jpQLDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLDMMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(true);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(white);
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLDMMouseClicked

    private void jpQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLKHMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(true);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(white);
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLKHMouseClicked

    private void jpTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTKMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(true);
        
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(white);
    }//GEN-LAST:event_jpTKMouseClicked

    private void jpQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLTKMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(false);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(true);
        this.jpViewTK.setVisible(false);
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(new Color(255,102,0));
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(white);
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLTKMouseClicked

    private void jpQLKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLKMMouseClicked
        this.jpViewQLBH.setVisible(false);
        this.jpViewQLDM.setVisible(false);
        this.jpViewQLKH.setVisible(false);
        this.jpViewQLKM.setVisible(true);
        this.jpViewQLSP.setVisible(false);
        this.jpViewQLTK.setVisible(false);
        this.jpViewTK.setVisible(false);
        
        this.jpQLBH.setBackground(new Color(255,102,0));
        this.jpQLDM.setBackground(new Color(255,102,0));
        this.jpQLKH.setBackground(new Color(255,102,0));
        this.jpQLKM.setBackground(white);
        this.jpQLSP.setBackground(new Color(255,102,0));
        this.jpQLTK.setBackground(new Color(255,102,0));
        this.jpTK.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_jpQLKMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpContainer;
    private javax.swing.JPanel jpQLBH;
    private javax.swing.JPanel jpQLDM;
    private javax.swing.JPanel jpQLKH;
    private javax.swing.JPanel jpQLKM;
    private javax.swing.JPanel jpQLSP;
    private javax.swing.JPanel jpQLTK;
    private javax.swing.JPanel jpTK;
    private javax.swing.JPanel jpViewQLBH;
    private javax.swing.JPanel jpViewQLDM;
    private javax.swing.JPanel jpViewQLKH;
    private javax.swing.JPanel jpViewQLKM;
    private javax.swing.JPanel jpViewQLSP;
    private javax.swing.JPanel jpViewQLTK;
    private javax.swing.JPanel jpViewTK;
    // End of variables declaration//GEN-END:variables
}
